#ifndef WOULDURATHERCREATOR_CONFIG_HPP
#define WOULDURATHERCREATOR_CONFIG_HPP
#include <iostream>
#include <iomanip>
#include <string>
#include <vector>
#include <unordered_map>
#include <regex>
#include <exception>
#include <csignal>
#include <cstdio>
#include <ctime>
#include <thread>
#include <cstdlib>
#include <boost/algorithm/string.hpp>
#include <unistd.h>
#include <tgbot/tgbot.h>
#include <sys/prctl.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <poll.h>
#endif //WOULDURATHERCREATOR_CONFIG_HPP
